[INFO][0][<module>] Linux derecho6 5.14.21-150400.24.18-default #1 SMP PREEMPT_DYNAMIC Thu Aug 4 14:17:48 UTC 2022 (e9f7bfc) x86_64 x86_64
[INFO][0][<module>] /glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB (2.7)
[INFO][0][<module>] /glade/u/apps/opt/conda/envs/npl/lib/python3.9/site-packages/numpy (1.23.5)
[INFO][0][<module>] /glade/u/apps/opt/conda/envs/npl/lib/python3.9/site-packages/matplotlib (3.6.3)
[INFO][0][<module>] /glade/u/apps/opt/conda/envs/npl/lib/python3.9/site-packages/netCDF4 (1.6.2)
[INFO][0][<module>] /glade/u/apps/opt/conda/envs/npl/lib/python3.9/site-packages/cf_units (3.1.1)
[INFO][0][<module>] /glade/u/home/rfisher/.local/lib/python3.9/site-packages/sympy (1.12)
[INFO][0][<module>] /glade/u/apps/opt/conda/envs/npl/lib/python3.9/site-packages/mpi4py (3.1.4)
[INFO][0][<module>] 2024-01-09 08:46:17.402703
[DEBUG][7][WorkConfront][Albedo/GEWEX.SRB][ctsm51fates_derecho_2s_nocomp_detsort]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/fates-global-cal/ilamb_scripts/./ilamb-run", line 385, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 157, in confront
    obs, mod, obs_timeint, mod_timeint = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 44, in stageData
    dn_obs = Variable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Variable.py", line 140, in __init__
    out = il.FromNetCDF4(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 724, in FromNetCDF4
    dset = Dataset(filename, mode="r")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/glade/work/rfisher/ILAMB_data/DATA/rsds/GEWEX.SRB/rsds_0.5x0.5.nc'

[DEBUG][6][WorkConfront][Albedo/CERES][ctsm51fates_derecho_2s_nocomp_detsort]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/fates-global-cal/ilamb_scripts/./ilamb-run", line 385, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 157, in confront
    obs, mod, obs_timeint, mod_timeint = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 44, in stageData
    dn_obs = Variable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Variable.py", line 140, in __init__
    out = il.FromNetCDF4(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 724, in FromNetCDF4
    dset = Dataset(filename, mode="r")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/glade/work/rfisher/ILAMB_data/DATA/rsds/CERESed4.2/rsds.nc'

[DEBUG][7][WorkConfront][Albedo/GEWEX.SRB][ctsm51fates_derecho_2s_nocomp]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/fates-global-cal/ilamb_scripts/./ilamb-run", line 385, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 157, in confront
    obs, mod, obs_timeint, mod_timeint = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 44, in stageData
    dn_obs = Variable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Variable.py", line 140, in __init__
    out = il.FromNetCDF4(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 724, in FromNetCDF4
    dset = Dataset(filename, mode="r")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/glade/work/rfisher/ILAMB_data/DATA/rsds/GEWEX.SRB/rsds_0.5x0.5.nc'

[DEBUG][6][WorkConfront][Albedo/CERES][ctsm51fates_derecho_2s_nocomp]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/fates-global-cal/ilamb_scripts/./ilamb-run", line 385, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 157, in confront
    obs, mod, obs_timeint, mod_timeint = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 44, in stageData
    dn_obs = Variable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Variable.py", line 140, in __init__
    out = il.FromNetCDF4(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 724, in FromNetCDF4
    dset = Dataset(filename, mode="r")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/glade/work/rfisher/ILAMB_data/DATA/rsds/CERESed4.2/rsds.nc'

[DEBUG][6][WorkConfront][Albedo/CERES][ctsm51fates_derecho_norman_nocomp]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/fates-global-cal/ilamb_scripts/./ilamb-run", line 385, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 157, in confront
    obs, mod, obs_timeint, mod_timeint = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 44, in stageData
    dn_obs = Variable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Variable.py", line 140, in __init__
    out = il.FromNetCDF4(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 724, in FromNetCDF4
    dset = Dataset(filename, mode="r")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/glade/work/rfisher/ILAMB_data/DATA/rsds/CERESed4.2/rsds.nc'

[DEBUG][7][WorkConfront][Albedo/GEWEX.SRB][ctsm51fates_derecho_norman_nocomp]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/fates-global-cal/ilamb_scripts/./ilamb-run", line 385, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 157, in confront
    obs, mod, obs_timeint, mod_timeint = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 44, in stageData
    dn_obs = Variable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Variable.py", line 140, in __init__
    out = il.FromNetCDF4(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 724, in FromNetCDF4
    dset = Dataset(filename, mode="r")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/glade/work/rfisher/ILAMB_data/DATA/rsds/GEWEX.SRB/rsds_0.5x0.5.nc'

[DEBUG][6][WorkConfront][Albedo/CERES][ctsm51fates_derecho_norman_nocomp]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/fates-global-cal/ilamb_scripts/./ilamb-run", line 385, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 157, in confront
    obs, mod, obs_timeint, mod_timeint = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 44, in stageData
    dn_obs = Variable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Variable.py", line 140, in __init__
    out = il.FromNetCDF4(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 724, in FromNetCDF4
    dset = Dataset(filename, mode="r")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/glade/work/rfisher/ILAMB_data/DATA/rsds/CERESed4.2/rsds.nc'

[DEBUG][7][WorkConfront][Albedo/GEWEX.SRB][ctsm51fates_derecho_norman_nocomp]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/fates-global-cal/ilamb_scripts/./ilamb-run", line 385, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 157, in confront
    obs, mod, obs_timeint, mod_timeint = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 44, in stageData
    dn_obs = Variable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Variable.py", line 140, in __init__
    out = il.FromNetCDF4(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 724, in FromNetCDF4
    dset = Dataset(filename, mode="r")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/glade/work/rfisher/ILAMB_data/DATA/rsds/GEWEX.SRB/rsds_0.5x0.5.nc'

[DEBUG][6][WorkConfront][Albedo/CERES][RTM_ens36_case_0]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/fates-global-cal/ilamb_scripts/./ilamb-run", line 385, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 157, in confront
    obs, mod, obs_timeint, mod_timeint = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 44, in stageData
    dn_obs = Variable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Variable.py", line 140, in __init__
    out = il.FromNetCDF4(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 724, in FromNetCDF4
    dset = Dataset(filename, mode="r")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/glade/work/rfisher/ILAMB_data/DATA/rsds/CERESed4.2/rsds.nc'

[DEBUG][7][WorkConfront][Albedo/GEWEX.SRB][RTM_ens36_case_0]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/fates-global-cal/ilamb_scripts/./ilamb-run", line 385, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 157, in confront
    obs, mod, obs_timeint, mod_timeint = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 44, in stageData
    dn_obs = Variable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Variable.py", line 140, in __init__
    out = il.FromNetCDF4(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 724, in FromNetCDF4
    dset = Dataset(filename, mode="r")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/glade/work/rfisher/ILAMB_data/DATA/rsds/GEWEX.SRB/rsds_0.5x0.5.nc'

[DEBUG][1][extractTimeSeries][ctsm51fates_derecho_2s_nocomp_detsort] Could not find [FATES_FRACTION] in the model results
[DEBUG][0][extractTimeSeries][ctsm51fates_derecho_2s_nocomp_detsort] Could not find [FATES_VEGC] in the model results
[DEBUG][1][WorkConfront][Biomass/NBCD2000][ctsm51fates_derecho_2s_nocomp_detsort]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/fates-global-cal/ilamb_scripts/./ilamb-run", line 385, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][0][WorkConfront][Biomass/GlobalCarbon][ctsm51fates_derecho_2s_nocomp_detsort]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/fates-global-cal/ilamb_scripts/./ilamb-run", line 385, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][5][extractTimeSeries][ctsm51fates_derecho_2s_nocomp_detsort] Could not find [hfls,le,EFLX_LH_TOT] in the model results
[DEBUG][5][WorkConfront][LatentHeat/WECANN][ctsm51fates_derecho_2s_nocomp_detsort]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/fates-global-cal/ilamb_scripts/./ilamb-run", line 385, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][1][extractTimeSeries][RTM_ens36_case_0] Could not find [FATES_FRACTION] in the model results
[DEBUG][1][WorkConfront][Biomass/NBCD2000][RTM_ens36_case_0]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/fates-global-cal/ilamb_scripts/./ilamb-run", line 385, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][1][extractTimeSeries][ctsm51fates_derecho_2s_nocomp_detsort] Could not find [FATES_FRACTION] in the model results
[DEBUG][1][WorkConfront][Biomass/USForest][ctsm51fates_derecho_2s_nocomp_detsort]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/fates-global-cal/ilamb_scripts/./ilamb-run", line 385, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][2][extractTimeSeries][RTM_ens36_case_0] Could not find [FATES_VEGC] in the model results
[DEBUG][2][WorkConfront][Biomass/ESACCI][RTM_ens36_case_0]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/fates-global-cal/ilamb_scripts/./ilamb-run", line 385, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][2][extractTimeSeries][ctsm51fates_derecho_2s_nocomp_detsort] Could not find [FATES_NEP] in the model results
[DEBUG][2][WorkConfront][NetEcosystemExchange/FLUXNET2015][ctsm51fates_derecho_2s_nocomp_detsort]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/fates-global-cal/ilamb_scripts/./ilamb-run", line 385, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][5][extractTimeSeries][RTM_ens36_case_0] Could not find [hfls,le,EFLX_LH_TOT] in the model results
[DEBUG][5][WorkConfront][LatentHeat/WECANN][RTM_ens36_case_0]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/fates-global-cal/ilamb_scripts/./ilamb-run", line 385, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][1][extractTimeSeries][RTM_ens36_case_0] Could not find [FATES_FRACTION] in the model results
[DEBUG][1][WorkConfront][Biomass/USForest][RTM_ens36_case_0]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/fates-global-cal/ilamb_scripts/./ilamb-run", line 385, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][1][extractTimeSeries][ctsm51fates_derecho_2s_nocomp_detsort] Could not find [FATES_FRACTION] in the model results
[DEBUG][1][WorkConfront][Biomass/ESACCI][ctsm51fates_derecho_2s_nocomp_detsort]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/fates-global-cal/ilamb_scripts/./ilamb-run", line 385, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][3][extractTimeSeries][ctsm51fates_derecho_2s_nocomp_detsort] Could not find [FATES_FRACTION] in the model results
[DEBUG][3][WorkConfront][EcosystemRespiration/FLUXCOM][ctsm51fates_derecho_2s_nocomp_detsort]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/fates-global-cal/ilamb_scripts/./ilamb-run", line 385, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][5][extractTimeSeries][ctsm51fates_derecho_2s_nocomp_detsort] Could not find [hfss,sh,FSH] in the model results
[DEBUG][5][WorkConfront][SensibleHeat/Fluxcom][ctsm51fates_derecho_2s_nocomp_detsort]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/fates-global-cal/ilamb_scripts/./ilamb-run", line 385, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][5][extractTimeSeries][ctsm51fates_derecho_2s_nocomp_detsort] Could not find [hfss,sh,FSH] in the model results
[DEBUG][5][WorkConfront][SensibleHeat/WECANN][ctsm51fates_derecho_2s_nocomp_detsort]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/fates-global-cal/ilamb_scripts/./ilamb-run", line 385, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][5][extractTimeSeries][RTM_ens36_case_0] Could not find [hfss,sh,FSH] in the model results
[DEBUG][5][WorkConfront][SensibleHeat/WECANN][RTM_ens36_case_0]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/fates-global-cal/ilamb_scripts/./ilamb-run", line 385, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][2][extractTimeSeries][RTM_ens36_case_0] Could not find [FATES_NEP] in the model results
[DEBUG][2][WorkConfront][NetEcosystemExchange/FLUXNET2015][RTM_ens36_case_0]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/fates-global-cal/ilamb_scripts/./ilamb-run", line 385, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][2][extractTimeSeries][ctsm51fates_derecho_2s_nocomp_detsort] Could not find [FATES_FRACTION] in the model results
[DEBUG][2][WorkConfront][EcosystemRespiration/FLUXNET2015][ctsm51fates_derecho_2s_nocomp_detsort]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/fates-global-cal/ilamb_scripts/./ilamb-run", line 385, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][2][extractTimeSeries][RTM_ens36_case_0] Could not find [FATES_FRACTION] in the model results
[DEBUG][2][WorkConfront][EcosystemRespiration/FLUXNET2015][RTM_ens36_case_0]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/fates-global-cal/ilamb_scripts/./ilamb-run", line 385, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][4][extractTimeSeries][RTM_ens36_case_0] Could not find [QVEGT] in the model results
[DEBUG][4][WorkConfront][Evapotranspiration/MODIS][RTM_ens36_case_0]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/fates-global-cal/ilamb_scripts/./ilamb-run", line 385, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][4][extractTimeSeries][ctsm51fates_derecho_2s_nocomp_detsort] Could not find [hfls,le,EFLX_LH_TOT] in the model results
[DEBUG][4][WorkConfront][LatentHeat/FLUXCOM][ctsm51fates_derecho_2s_nocomp_detsort]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/fates-global-cal/ilamb_scripts/./ilamb-run", line 385, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][0][WorkConfront][Biomass/GlobalCarbon][ctsm51fates_derecho_2s_nocomp]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/fates-global-cal/ilamb_scripts/./ilamb-run", line 385, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 558, in derivedVariable
    return Variable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Variable.py", line 192, in __init__
    self.dt = (self.time_bnds[:, 1] - self.time_bnds[:, 0]).mean()
  File "/glade/u/apps/opt/conda/envs/npl/lib/python3.9/site-packages/numpy/core/_methods.py", line 190, in _mean
    ret = ret.dtype.type(ret / rcount)
FloatingPointError: invalid value encountered in double_scalars

[INFO][4][MakeComparable][LatentHeat/FLUXCOM][ctsm51fates_derecho_2s_nocomp] Spatial data was clipped from the reference:  before: [420 360 720] after: [420 360 711]
[DEBUG][0][WorkConfront][Biomass/GlobalCarbon][ctsm51fates_derecho_norman_nocomp]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/fates-global-cal/ilamb_scripts/./ilamb-run", line 385, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 558, in derivedVariable
    return Variable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Variable.py", line 192, in __init__
    self.dt = (self.time_bnds[:, 1] - self.time_bnds[:, 0]).mean()
  File "/glade/u/apps/opt/conda/envs/npl/lib/python3.9/site-packages/numpy/core/_methods.py", line 190, in _mean
    ret = ret.dtype.type(ret / rcount)
FloatingPointError: invalid value encountered in double_scalars

[INFO][3][MakeComparable][EcosystemRespiration/FLUXCOM][ctsm51fates_derecho_norman_nocomp] Spatial data was clipped from the reference:  before: [408 360 720] after: [408 360 711]
[DEBUG][0][WorkConfront][Biomass/GlobalCarbon][ctsm51fates_derecho_norman_nocomp]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/fates-global-cal/ilamb_scripts/./ilamb-run", line 385, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 558, in derivedVariable
    return Variable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Variable.py", line 192, in __init__
    self.dt = (self.time_bnds[:, 1] - self.time_bnds[:, 0]).mean()
  File "/glade/u/apps/opt/conda/envs/npl/lib/python3.9/site-packages/numpy/core/_methods.py", line 190, in _mean
    ret = ret.dtype.type(ret / rcount)
FloatingPointError: invalid value encountered in double_scalars

[DEBUG][0][extractTimeSeries][RTM_ens36_case_0] Could not find [FATES_VEGC] in the model results
[DEBUG][0][WorkConfront][Biomass/GlobalCarbon][RTM_ens36_case_0]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/fates-global-cal/ilamb_scripts/./ilamb-run", line 385, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][4][AnalysisMeanStateSpace][hfls] Bias scored using Collier2018
[INFO][4][AnalysisMeanStateSpace][hfls] RMSE scored using Collier2018
[INFO][4][confront][LatentHeat/FLUXCOM][ctsm51fates_derecho_2s_nocomp] Success
[INFO][3][AnalysisMeanStateSpace][reco] Bias scored using Collier2018
[INFO][3][AnalysisMeanStateSpace][reco] RMSE scored using Collier2018
[INFO][4][MakeComparable][LatentHeat/FLUXCOM][ctsm51fates_derecho_norman_nocomp] Spatial data was clipped from the reference:  before: [420 360 720] after: [420 360 711]
[INFO][3][confront][EcosystemRespiration/FLUXCOM][ctsm51fates_derecho_norman_nocomp] Success
[INFO][3][MakeComparable][EcosystemRespiration/FLUXCOM][ctsm51fates_derecho_norman_nocomp] Spatial data was clipped from the reference:  before: [408 360 720] after: [408 360 711]
[INFO][4][AnalysisMeanStateSpace][hfls] Bias scored using Collier2018
[INFO][4][AnalysisMeanStateSpace][hfls] RMSE scored using Collier2018
[INFO][4][confront][LatentHeat/FLUXCOM][ctsm51fates_derecho_norman_nocomp] Success
[INFO][3][AnalysisMeanStateSpace][reco] Bias scored using Collier2018
[INFO][3][AnalysisMeanStateSpace][reco] RMSE scored using Collier2018
[INFO][3][confront][EcosystemRespiration/FLUXCOM][ctsm51fates_derecho_norman_nocomp] Success
[INFO][4][MakeComparable][LatentHeat/FLUXCOM][ctsm51fates_derecho_norman_nocomp] Spatial data was clipped from the reference:  before: [420 360 720] after: [420 360 711]
[DEBUG][3][extractTimeSeries][ctsm51fates_derecho_2s_nocomp_detsort] Could not find [FPSN,gpp,FATES_GPP] in the model results
[DEBUG][3][WorkConfront][GrossPrimaryProductivity/GBAF][ctsm51fates_derecho_2s_nocomp_detsort]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/fates-global-cal/ilamb_scripts/./ilamb-run", line 385, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][3][extractTimeSeries][ctsm51fates_derecho_2s_nocomp_detsort] Could not find [QSOIL] in the model results
[DEBUG][3][WorkConfront][Evapotranspiration/MODIS][ctsm51fates_derecho_2s_nocomp_detsort]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/fates-global-cal/ilamb_scripts/./ilamb-run", line 385, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][4][AnalysisMeanStateSpace][hfls] Bias scored using Collier2018
[INFO][4][AnalysisMeanStateSpace][hfls] RMSE scored using Collier2018
[INFO][4][confront][LatentHeat/FLUXCOM][ctsm51fates_derecho_norman_nocomp] Success
[INFO][4][MakeComparable][LatentHeat/FLUXCOM][RTM_ens36_case_0] Spatial data was clipped from the reference:  before: [420 360 720] after: [420 360 711]
