[INFO][0][<module>] Linux derecho2 5.14.21-150400.24.18-default #1 SMP PREEMPT_DYNAMIC Thu Aug 4 14:17:48 UTC 2022 (e9f7bfc) x86_64 x86_64
[INFO][0][<module>] /glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB (2.7)
[INFO][0][<module>] /glade/u/apps/opt/conda/envs/npl/lib/python3.9/site-packages/numpy (1.23.5)
[INFO][0][<module>] /glade/u/apps/opt/conda/envs/npl/lib/python3.9/site-packages/matplotlib (3.6.3)
[INFO][0][<module>] /glade/u/apps/opt/conda/envs/npl/lib/python3.9/site-packages/netCDF4 (1.6.2)
[INFO][0][<module>] /glade/u/apps/opt/conda/envs/npl/lib/python3.9/site-packages/cf_units (3.1.1)
[INFO][0][<module>] /glade/u/home/rfisher/.local/lib/python3.9/site-packages/sympy (1.12)
[INFO][0][<module>] /glade/u/apps/opt/conda/envs/npl/lib/python3.9/site-packages/mpi4py (3.1.4)
[INFO][0][<module>] 2024-01-09 05:27:52.001121
[DEBUG][7][WorkConfront][Albedo/CERES][ctsm51fates_derecho_norman_sp]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/fates-global-cal/ilamb_scripts/./ilamb-run", line 385, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 157, in confront
    obs, mod, obs_timeint, mod_timeint = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 44, in stageData
    dn_obs = Variable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Variable.py", line 140, in __init__
    out = il.FromNetCDF4(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 724, in FromNetCDF4
    dset = Dataset(filename, mode="r")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/glade/work/rfisher/ILAMB_data/DATA/rsds/CERESed4.2/rsds.nc'

[DEBUG][7][WorkConfront][Albedo/GEWEX.SRB][ctsm51fates_derecho_2s_sp]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/fates-global-cal/ilamb_scripts/./ilamb-run", line 385, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 157, in confront
    obs, mod, obs_timeint, mod_timeint = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 44, in stageData
    dn_obs = Variable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Variable.py", line 140, in __init__
    out = il.FromNetCDF4(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 724, in FromNetCDF4
    dset = Dataset(filename, mode="r")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/glade/work/rfisher/ILAMB_data/DATA/rsds/GEWEX.SRB/rsds_0.5x0.5.nc'

[DEBUG][7][WorkConfront][Albedo/GEWEX.SRB][ctsm51fates_derecho_norman_sp]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/fates-global-cal/ilamb_scripts/./ilamb-run", line 385, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 157, in confront
    obs, mod, obs_timeint, mod_timeint = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 44, in stageData
    dn_obs = Variable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Variable.py", line 140, in __init__
    out = il.FromNetCDF4(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 724, in FromNetCDF4
    dset = Dataset(filename, mode="r")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/glade/work/rfisher/ILAMB_data/DATA/rsds/GEWEX.SRB/rsds_0.5x0.5.nc'

[DEBUG][1][WorkConfront][EvaporativeFraction/GBAF][ctsm51fates_derecho_norman_sp]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/fates-global-cal/ilamb_scripts/./ilamb-run", line 385, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfEvapFraction.py", line 168, in confront
    obs, mod, obs_timeint, mod_timeint = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfEvapFraction.py", line 58, in stageData
    le_obs = Variable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Variable.py", line 140, in __init__
    out = il.FromNetCDF4(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 724, in FromNetCDF4
    dset = Dataset(filename, mode="r")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/glade/work/rfisher/ILAMB_data/DATA/hfls/FLUXCOM/lh.nc'

[INFO][2][MakeComparable][LatentHeat/WECANN][ctsm51fates_derecho_2s_sp] Spatial data was clipped from the reference:  before: [108 180 360] after: [108 180 356]
[INFO][1][MakeComparable][LatentHeat/Fluxcom][ctsm51fates_derecho_2s_sp] Spatial data was clipped from the reference:  before: [420 360 720] after: [420 360 711]
[DEBUG][6][extractTimeSeries][ctsm51fates_derecho_2s_sp] Could not find [tsl] in the model results
[DEBUG][6][WorkConfront][Permafrost/NSIDC][ctsm51fates_derecho_2s_sp]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/fates-global-cal/ilamb_scripts/./ilamb-run", line 385, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfPermafrost.py", line 230, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfPermafrost.py", line 192, in stageData
    tsl = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][0][MakeComparable][Evapotranspiration/GLEAM][ctsm51fates_derecho_2s_sp] Spatial data was clipped from the reference:  before: [468 360 720] after: [468 360 711]
[INFO][4][MakeComparable][SensibleHeat/Fluxcom][ctsm51fates_derecho_norman_sp] Spatial data was clipped from the reference:  before: [420 360 720] after: [420 360 711]
[INFO][2][AnalysisMeanStateSpace][hfls] Bias scored using Collier2018
[DEBUG][6][extractTimeSeries][ctsm51fates_derecho_norman_sp] Could not find [tsl] in the model results
[DEBUG][6][WorkConfront][Permafrost/NSIDC][ctsm51fates_derecho_norman_sp]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/fates-global-cal/ilamb_scripts/./ilamb-run", line 385, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfPermafrost.py", line 230, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfPermafrost.py", line 192, in stageData
    tsl = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][6][WorkConfront][Albedo/CERES][ctsm51fates_derecho_2s_sp]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/fates-global-cal/ilamb_scripts/./ilamb-run", line 385, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 157, in confront
    obs, mod, obs_timeint, mod_timeint = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 44, in stageData
    dn_obs = Variable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Variable.py", line 140, in __init__
    out = il.FromNetCDF4(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 724, in FromNetCDF4
    dset = Dataset(filename, mode="r")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/glade/work/rfisher/ILAMB_data/DATA/rsds/CERESed4.2/rsds.nc'

[INFO][2][AnalysisMeanStateSpace][hfls] RMSE scored using Collier2018
[INFO][2][confront][LatentHeat/WECANN][ctsm51fates_derecho_2s_sp] Success
[INFO][3][MakeComparable][SensibleHeat/Fluxcom][ctsm51fates_derecho_2s_sp] Spatial data was clipped from the reference:  before: [420 360 720] after: [420 360 711]
[INFO][2][MakeComparable][LatentHeat/WECANN][ctsm51fates_derecho_norman_sp] Spatial data was clipped from the reference:  before: [108 180 360] after: [108 180 356]
[INFO][1][AnalysisMeanStateSpace][hfls] Bias scored using Collier2018
[INFO][2][AnalysisMeanStateSpace][hfls] Bias scored using Collier2018
[INFO][2][AnalysisMeanStateSpace][hfls] RMSE scored using Collier2018
[INFO][2][confront][LatentHeat/WECANN][ctsm51fates_derecho_norman_sp] Success
[INFO][1][AnalysisMeanStateSpace][hfls] RMSE scored using Collier2018
[INFO][1][confront][LatentHeat/Fluxcom][ctsm51fates_derecho_2s_sp] Success
[INFO][4][AnalysisMeanStateSpace][hfss] Bias scored using Collier2018
[INFO][0][AnalysisMeanStateSpace][et] Bias scored using Collier2018
[INFO][4][AnalysisMeanStateSpace][hfss] RMSE scored using Collier2018
[INFO][4][confront][SensibleHeat/Fluxcom][ctsm51fates_derecho_norman_sp] Success
[INFO][0][AnalysisMeanStateSpace][et] RMSE scored using Collier2018
[INFO][0][confront][Evapotranspiration/GLEAM][ctsm51fates_derecho_2s_sp] Success
